name: 'Setup and Cleanup Provisioned Concurrency for AWS Lambda'
description: 'Sets up provisioned concurrency for a specified AWS Lambda function and cleans up older versions'
author: 'IronCloud'
branding:
  color: orange
  icon: arrow-up-right
inputs:
  function-name:
    description: 'Name of the AWS Lambda function'
    required: true
  provisioned-concurrency:
    description: 'Number of provisioned concurrency'
    required: true
outputs:
  new-version:
    description: 'The new version number of the Lambda function'
  provisioned-concurrency:
    description: 'The provisioned concurrency count that was set'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/src/entrypoint.sh
      shell: bash
      env:
        INPUT_FUNCTION_NAME: ${{ inputs.function-name }}
        INPUT_PROVISIONED_CONCURRENCY: ${{ inputs.provisioned-concurrency }}
